// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cabdgguxdewqwyggwyrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhYmRnZ3V4ZGV3cXd5Z2d3eXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjAwNjEsImV4cCI6MjA2ODgzNjA2MX0.p33hGYIB602j-a927zufQ1PqDbb3uYvExBKXp07rG3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});